module.exports = [
  { category: 'Technology', difficulty: 'Easy', question: 'What does "CPU" stand for?', options: ['Central Processing Unit', 'Computer Personal Unit', 'Central Program Utility', 'Core Processing Utility'], correctIndex: 0 },
  { category: 'Technology', difficulty: 'Easy', question: 'Which company created the iPhone?', options: ['Samsung', 'Google', 'Apple', 'Microsoft'], correctIndex: 2 },
  { category: 'Technology', difficulty: 'Easy', question: 'What does "WWW" stand for in a URL?', options: ['World Wide Web', 'Wide Web World', 'Web World Wide', 'Wireless Web World'], correctIndex: 0 },
  { category: 'Technology', difficulty: 'Easy', question: 'Which language is primarily used for web styling?', options: ['Python', 'CSS', 'Java', 'C++'], correctIndex: 1 },
  { category: 'Technology', difficulty: 'Easy', question: 'What is the main function of RAM?', options: ['Permanent storage', 'Temporary memory', 'Display graphics', 'Network connection'], correctIndex: 1 },
  { category: 'Technology', difficulty: 'Medium', question: 'What does API stand for?', options: ['Application Programming Interface', 'Automated Program Integration', 'Advanced Protocol Internet', 'Application Process Index'], correctIndex: 0 },
  { category: 'Technology', difficulty: 'Medium', question: 'Which protocol secures HTTPS connections?', options: ['FTP', 'TLS/SSL', 'SMTP', 'DNS'], correctIndex: 1 },
  { category: 'Technology', difficulty: 'Medium', question: 'What year was the first iPhone released?', options: ['2005', '2007', '2009', '2010'], correctIndex: 1 },
  { category: 'Technology', difficulty: 'Medium', question: 'Which database type is MongoDB?', options: ['Relational', 'Document-oriented', 'Graph', 'Column-family'], correctIndex: 1 },
  { category: 'Technology', difficulty: 'Medium', question: 'What does GPU primarily accelerate?', options: ['Text editing', 'Graphics rendering', 'File compression', 'Email delivery'], correctIndex: 1 },
  { category: 'Technology', difficulty: 'Hard', question: 'Who is credited with inventing the World Wide Web?', options: ['Bill Gates', 'Tim Berners-Lee', 'Steve Jobs', 'Linus Torvalds'], correctIndex: 1 },
  { category: 'Technology', difficulty: 'Hard', question: 'What is the time complexity of binary search?', options: ['O(n)', 'O(log n)', 'O(n²)', 'O(1)'], correctIndex: 1 },
  { category: 'Technology', difficulty: 'Hard', question: 'Which encryption algorithm is commonly used in Bitcoin?', options: ['RSA', 'AES', 'SHA-256', 'MD5'], correctIndex: 2 },
  { category: 'Technology', difficulty: 'Hard', question: 'What does CAP theorem stand for in distributed systems?', options: ['Consistency, Availability, Partition tolerance', 'Cache, Access, Protocol', 'Compute, Analyze, Process', 'Connection, Auth, Privacy'], correctIndex: 0 },
  { category: 'Technology', difficulty: 'Hard', question: 'Which programming paradigm does React hooks emphasize?', options: ['Object-oriented only', 'Functional', 'Procedural', 'Logic'], correctIndex: 1 },
  { category: 'Sports', difficulty: 'Easy', question: 'How many players are on a standard soccer team on the field?', options: ['9', '10', '11', '12'], correctIndex: 2 },
  { category: 'Sports', difficulty: 'Easy', question: 'Which sport uses a racket and shuttlecock?', options: ['Tennis', 'Badminton', 'Squash', 'Cricket'], correctIndex: 1 },
  { category: 'Sports', difficulty: 'Easy', question: 'In basketball, how many points is a free throw worth?', options: ['1', '2', '3', '4'], correctIndex: 0 },
  { category: 'Sports', difficulty: 'Easy', question: 'Which country hosts Wimbledon?', options: ['USA', 'France', 'England', 'Australia'], correctIndex: 2 },
  { category: 'Sports', difficulty: 'Easy', question: 'What color is the center of an archery target?', options: ['Red', 'Blue', 'Gold/Yellow', 'Green'], correctIndex: 2 },
  { category: 'Sports', difficulty: 'Medium', question: 'How long is a marathon in kilometers (approximately)?', options: ['21', '32', '42', '50'], correctIndex: 2 },
  { category: 'Sports', difficulty: 'Medium', question: 'Which NBA player is known as "The King"?', options: ['Michael Jordan', 'LeBron James', 'Kobe Bryant', 'Stephen Curry'], correctIndex: 1 },
  { category: 'Sports', difficulty: 'Medium', question: 'In cricket, how many balls are in one over?', options: ['4', '5', '6', '8'], correctIndex: 2 },
  { category: 'Sports', difficulty: 'Medium', question: 'Which Grand Slam is played on clay courts?', options: ['Wimbledon', 'US Open', 'French Open', 'Australian Open'], correctIndex: 2 },
  { category: 'Sports', difficulty: 'Medium', question: 'What is the maximum score in a single frame of ten-pin bowling?', options: ['20', '30', '40', '50'], correctIndex: 1 },
  { category: 'Sports', difficulty: 'Hard', question: 'Who holds the record for most Olympic gold medals?', options: ['Usain Bolt', 'Michael Phelps', 'Carl Lewis', 'Simone Biles'], correctIndex: 1 },
  { category: 'Sports', difficulty: 'Hard', question: 'In which year were the first modern Olympic Games held?', options: ['1896', '1900', '1912', '1924'], correctIndex: 0 },
  { category: 'Sports', difficulty: 'Hard', question: 'What is the diameter of a basketball hoop in inches?', options: ['16', '18', '20', '22'], correctIndex: 1 },
  { category: 'Sports', difficulty: 'Hard', question: 'Which football club has won the most UEFA Champions League titles?', options: ['AC Milan', 'Barcelona', 'Real Madrid', 'Bayern Munich'], correctIndex: 2 },
  { category: 'Sports', difficulty: 'Hard', question: 'What is the term for three strikes in a row in bowling?', options: ['Spare', 'Turkey', 'Strikeout', 'Hat trick'], correctIndex: 1 },
  { category: 'General Knowledge', difficulty: 'Easy', question: 'What is the capital of France?', options: ['Berlin', 'Madrid', 'Paris', 'Rome'], correctIndex: 2 },
  { category: 'General Knowledge', difficulty: 'Easy', question: 'How many continents are there?', options: ['5', '6', '7', '8'], correctIndex: 2 },
  { category: 'General Knowledge', difficulty: 'Easy', question: 'What is the largest ocean on Earth?', options: ['Atlantic', 'Indian', 'Arctic', 'Pacific'], correctIndex: 3 },
  { category: 'General Knowledge', difficulty: 'Easy', question: 'Which planet is known as the Red Planet?', options: ['Venus', 'Mars', 'Jupiter', 'Saturn'], correctIndex: 1 },
  { category: 'General Knowledge', difficulty: 'Easy', question: 'What is the chemical symbol for water?', options: ['O2', 'H2O', 'CO2', 'NaCl'], correctIndex: 1 },
  { category: 'General Knowledge', difficulty: 'Medium', question: 'Which country has the largest population?', options: ['India', 'USA', 'China', 'Indonesia'], correctIndex: 0 },
  { category: 'General Knowledge', difficulty: 'Medium', question: 'Who painted the Mona Lisa?', options: ['Michelangelo', 'Leonardo da Vinci', 'Raphael', 'Donatello'], correctIndex: 1 },
  { category: 'General Knowledge', difficulty: 'Medium', question: 'What is the longest river in the world?', options: ['Amazon', 'Nile', 'Yangtze', 'Mississippi'], correctIndex: 1 },
  { category: 'General Knowledge', difficulty: 'Medium', question: 'In which year did World War II end?', options: ['1943', '1944', '1945', '1946'], correctIndex: 2 },
  { category: 'General Knowledge', difficulty: 'Medium', question: 'What is the currency of Japan?', options: ['Won', 'Yuan', 'Yen', 'Ringgit'], correctIndex: 2 },
  { category: 'General Knowledge', difficulty: 'Hard', question: 'What is the smallest country in the world by area?', options: ['Monaco', 'Vatican City', 'San Marino', 'Liechtenstein'], correctIndex: 1 },
  { category: 'General Knowledge', difficulty: 'Hard', question: 'Who wrote "1984"?', options: ['Aldous Huxley', 'George Orwell', 'Ray Bradbury', 'H.G. Wells'], correctIndex: 1 },
  { category: 'General Knowledge', difficulty: 'Hard', question: 'What is the hardest natural substance on Earth?', options: ['Gold', 'Iron', 'Diamond', 'Platinum'], correctIndex: 2 },
  { category: 'General Knowledge', difficulty: 'Hard', question: 'Which ancient wonder was located in Alexandria?', options: ['Colossus', 'Lighthouse', 'Hanging Gardens', 'Mausoleum'], correctIndex: 1 },
  { category: 'General Knowledge', difficulty: 'Hard', question: 'What language has the most native speakers worldwide?', options: ['English', 'Spanish', 'Mandarin Chinese', 'Hindi'], correctIndex: 2 },
  { category: 'Movies', difficulty: 'Easy', question: 'Who directed "Jurassic Park"?', options: ['James Cameron', 'Steven Spielberg', 'Christopher Nolan', 'Quentin Tarantino'], correctIndex: 1 },
  { category: 'Movies', difficulty: 'Easy', question: 'Which movie features the character Iron Man?', options: ['Batman', 'Avengers', 'Superman', 'X-Men'], correctIndex: 1 },
  { category: 'Movies', difficulty: 'Easy', question: 'What is the highest-grossing film franchise?', options: ['Harry Potter', 'Star Wars', 'Marvel Cinematic Universe', 'James Bond'], correctIndex: 2 },
  { category: 'Movies', difficulty: 'Easy', question: 'In "The Lion King", what is Simba\'s father\'s name?', options: ['Scar', 'Mufasa', 'Rafiki', 'Zazu'], correctIndex: 1 },
  { category: 'Movies', difficulty: 'Easy', question: 'Which actor played Jack in "Titanic"?', options: ['Brad Pitt', 'Leonardo DiCaprio', 'Tom Cruise', 'Johnny Depp'], correctIndex: 1 },
  { category: 'Movies', difficulty: 'Medium', question: 'Which film won Best Picture at the 2020 Oscars?', options: ['1917', 'Joker', 'Parasite', 'Once Upon a Time'], correctIndex: 2 },
  { category: 'Movies', difficulty: 'Medium', question: 'Who composed the score for "Inception"?', options: ['John Williams', 'Hans Zimmer', 'Danny Elfman', 'Ennio Morricone'], correctIndex: 1 },
  { category: 'Movies', difficulty: 'Medium', question: 'What is the name of the fictional African country in "Black Panther"?', options: ['Zamunda', 'Wakanda', 'Genovia', 'Latveria'], correctIndex: 1 },
  { category: 'Movies', difficulty: 'Medium', question: 'Which studio created "Toy Story"?', options: ['DreamWorks', 'Pixar', 'Blue Sky', 'Illumination'], correctIndex: 1 },
  { category: 'Movies', difficulty: 'Medium', question: 'In "The Matrix", what color pill does Neo take?', options: ['Blue', 'Red', 'Green', 'Yellow'], correctIndex: 1 },
  { category: 'Movies', difficulty: 'Hard', question: 'Which film was the first to win 11 Academy Awards (tied record)?', options: ['Titanic', 'Ben-Hur', 'Lord of the Rings: ROTK', 'All of these'], correctIndex: 3 },
  { category: 'Movies', difficulty: 'Hard', question: 'Who directed "Pulp Fiction"?', options: ['Martin Scorsese', 'Quentin Tarantino', 'Coen Brothers', 'David Fincher'], correctIndex: 1 },
  { category: 'Movies', difficulty: 'Hard', question: 'What was the first feature-length animated movie?', options: ['Fantasia', 'Snow White', 'Pinocchio', 'Bambi'], correctIndex: 1 },
  { category: 'Movies', difficulty: 'Hard', question: 'Which actor has won the most Oscars for acting?', options: ['Meryl Streep', 'Daniel Day-Lewis', 'Katharine Hepburn', 'Jack Nicholson'], correctIndex: 2 },
  { category: 'Movies', difficulty: 'Hard', question: 'In "Fight Club", what is the first rule of Fight Club?', options: ['Always fight fair', 'You do not talk about Fight Club', 'No weapons', 'Respect the referee'], correctIndex: 1 },
  { category: 'Science', difficulty: 'Easy', question: 'What gas do plants absorb from the atmosphere?', options: ['Oxygen', 'Nitrogen', 'Carbon Dioxide', 'Hydrogen'], correctIndex: 2 },
  { category: 'Science', difficulty: 'Easy', question: 'How many bones are in the adult human body?', options: ['106', '206', '306', '406'], correctIndex: 1 },
  { category: 'Science', difficulty: 'Easy', question: 'What is the speed of light approximately (km/s)?', options: ['150,000', '200,000', '300,000', '400,000'], correctIndex: 2 },
  { category: 'Science', difficulty: 'Easy', question: 'What is the center of an atom called?', options: ['Electron', 'Proton', 'Nucleus', 'Neutron'], correctIndex: 2 },
  { category: 'Science', difficulty: 'Easy', question: 'Which organ pumps blood through the body?', options: ['Lungs', 'Brain', 'Heart', 'Liver'], correctIndex: 2 },
  { category: 'Science', difficulty: 'Medium', question: 'What is Newton\'s second law of motion?', options: ['F = ma', 'E = mc²', 'V = IR', 'PV = nRT'], correctIndex: 0 },
  { category: 'Science', difficulty: 'Medium', question: 'What is the most abundant gas in Earth\'s atmosphere?', options: ['Oxygen', 'Carbon Dioxide', 'Nitrogen', 'Argon'], correctIndex: 2 },
  { category: 'Science', difficulty: 'Medium', question: 'Which blood type is known as the universal donor?', options: ['A+', 'B-', 'AB+', 'O-'], correctIndex: 3 },
  { category: 'Science', difficulty: 'Medium', question: 'What particle has a positive charge?', options: ['Electron', 'Neutron', 'Proton', 'Photon'], correctIndex: 2 },
  { category: 'Science', difficulty: 'Medium', question: 'What is the chemical symbol for gold?', options: ['Go', 'Gd', 'Au', 'Ag'], correctIndex: 2 },
  { category: 'Science', difficulty: 'Hard', question: 'What is the powerhouse of the cell?', options: ['Nucleus', 'Ribosome', 'Mitochondria', 'Golgi apparatus'], correctIndex: 2 },
  { category: 'Science', difficulty: 'Hard', question: 'Who developed the theory of general relativity?', options: ['Newton', 'Einstein', 'Hawking', 'Bohr'], correctIndex: 1 },
  { category: 'Science', difficulty: 'Hard', question: 'What is the approximate age of the universe in billion years?', options: ['4.5', '13.8', '20', '50'], correctIndex: 1 },
  { category: 'Science', difficulty: 'Hard', question: 'Which element has the atomic number 1?', options: ['Helium', 'Hydrogen', 'Lithium', 'Carbon'], correctIndex: 1 },
  { category: 'Science', difficulty: 'Hard', question: 'What type of bond shares electrons between atoms?', options: ['Ionic', 'Covalent', 'Metallic', 'Hydrogen'], correctIndex: 1 },
];
